# Input file names without file extension
# Example: "Pa_Aug_4x"

v_chg_and_adj = "Charges_And_Adjustment_Jul_4x"
v_payments = "Payments_Jun_4x"
v_cct = "CCT_Information_Jun_4x"
v_discp_rates = "Discrepant_Rates_Jun_4x"
v_dnr1 = "DNR-1_Jun_4x"
v_dnr2 = "DNR-2_Jun_4x"
v_dnr3 = "DNR-3_Jun_4x"
v_grts_and_gst = "Gratis_And_GstCert_Report_Jun_4x"
v_gst_email = "Guest_Email_Jun_4x"
v_lldb = "LLDB_Jun_4x"
v_pay_and_ref = "Payments_And_Refunds_Jun_4x"
v_prop_over = "Property_Overview_Jun_4x"
v_room_moves = "Room_Moves_Jun_4x"
v_os_users = "Organization-Structure-Users_Jun"
v_os_properties = "Organization-Structure-Properties_Jun"
v_all_users = "All-Users-Data_Jun"
v_api = "4x"
